function rotatedIntersectionLines = getIntersectionRotatedLines(pgonCircleIntersectionLines, centerCoordinates)
  rotatedIntersectionLines = [];
  s = size(pgonCircleIntersectionLines,1);
  for i=1:s
    curLine = pgonCircleIntersectionLines(i,:);
    angle = 0;
    for a=1:5
      angle = angle + 3;
      [rotated_xs, rotated_ys] = rotateCoordinates(...
        [curLine(1,1) curLine(1,3)],...
        [curLine(1,2) curLine(1,4)],...
        centerCoordinates(1,1),...
        centerCoordinates(1,2),...
        angle);
      rotatedIntersectionLines = [...
        rotatedIntersectionLines;...
        [rotated_xs(1,1) rotated_ys(1,1) rotated_xs(1,2) rotated_ys(1,2)]...
        ];
    end
  end
end
